name: Build Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
    - name: Build executable
      run: dart compile exe bin/pnp_tool.dart -o pnp_card_${{ matrix.os }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pnp_card_${{ matrix.os }}
        path: pnp_card_${{ matrix.os }}